[package]
name = "pasture-core"
version = "0.1.0"
authors = ["Pascal Bormann <pascal.bormann@igd.fraunhofer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.23.1"
anyhow = "1.0.34"
float-ord = "0.2.0"
static_assertions = "1.1.0"