[package]
name = "pasture-core"
version = "0.1.0"
authors = ["Pascal Bormann <pascal.bormann@igd.fraunhofer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pasture-derive = {path = "../pasture-derive" }
nalgebra = {version = "0.23.1", features = ["serde-serialize"] }
anyhow = "1.0.34"
float-ord = "0.2.0"
static_assertions = "1.1.0"
lazy_static = "1.4.0"
serde = {version = "1.0.119", features = ["derive"] }
rayon = "1.5.0"
itertools = "0.10.0"

[dev-dependencies]
rand = "0.8.2"
criterion = "0.3"

[[bench]]
name = "point_buffer_iterators_bench"
harness = false