[package]
name = "pasture-algorithms"
version = "0.1.0"
authors = ["Pascal Bormann <pascal.bormann@igd.fraunhofer.de>"]
edition = "2018"

[dependencies]
pasture-core = { path = "../pasture-core" }
anyhow = "1.0.34"