[package]
name = "pasture-io"
version = "0.1.0"
authors = ["Pascal Bormann <pascal.bormann@igd.fraunhofer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pasture-core = { path = "../pasture-core" }
anyhow = "1.0.34"
las = { version = "0.7.3", features = ["laz"] }